name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'We will take care of this problem as soon as possible'' issue'
        pr-message: 'Please wait for a reveiwer to look at your PR'' pr'
